### PR TITLE
Update services.yml

### PR DESCRIPTION
**Pull request by rumours86**
On symfony 5.2.0 i have error

Script cache:clear returned with error code 1
!!  
!!  In YamlFileLoader.php line 745:
!!                                                                                 
!!    The file "vendor/pluk77/symfony-sphinx-bundle/Depend  
!!    encyInjection/../Resources/config/services.yml" does not contain valid YAML  
!!    : Malformed inline YAML string at line 28 (near "sphinx.manager: '@Pluk77\S  
!!    ymfonySphinxBundle\Sphinx\Manager' ")                                        
!!                                                                                 
!!  
!!  In Parser.php line 1216:
!!                                                                                 
!!    Malformed inline YAML string at line 28 (near "sphinx.manager: '@Pluk77\Sym  
!!    fonySphinxBundle\Sphinx\Manager' ")

### CODE REVIEW

**Comment by pluk77** [comment]
I am not sure if the problem is correctly fixed. The @ indicates a named service, which is named higher up in the same file. Line 9 has the same structure and does not cause an error.

Perhaps it has something to do with the line-ending?

**Comment by rumours86** [comment]
my changes fixed the error

**Comment by QaaDee** [comment]
remove the space at the end of line 28

**Comment by rumours86** [comment]
Thank you

**Review by pluk77 — APPROVED** [review]
Thanks for picking this up

**Pull request merged**
